# Generated by Django 3.1.7 on 2021-03-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_num', models.CharField(max_length=11)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_street', models.CharField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_state', models.CharField(max_length=2)),
                ('user_zip', models.CharField(max_length=10)),
                ('user_card_num', models.CharField(max_length=50)),
                ('user_card_exp', models.DateField()),
                ('user_card_seccode', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
