# Generated by Django 3.1.7 on 2021-03-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [

       
    ]
