# Generated by Django 3.1.7 on 2021-03-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210330_1025'),
    ]


