# Generated by Django 3.1.7 on 2021-03-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210330_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.TextField(null=True),
        ),
    ]
