# Generated by Django 3.1.7 on 2021-03-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('phone_num', models.CharField(max_length=11, null=True)),
                ('user_email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=50, null=True)),
                ('user_street', models.CharField(max_length=50, null=True)),
                ('user_city', models.CharField(max_length=50, null=True)),
                ('user_state', models.CharField(max_length=2, null=True)),
                ('user_zip', models.CharField(max_length=10, null=True)),
                ('user_card_num', models.CharField(max_length=50, null=True)),
                ('user_card_exp', models.DateField(null=True)),
                ('user_card_seccode', models.CharField(max_length=4, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.TextField(null=True),
        ),
    ]
