# Generated by Django 3.1.7 on 2021-03-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210330_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_card_seccode',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
