# Generated by Django 3.1.7 on 2021-03-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210331_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_zip',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
