# Generated by Django 3.1.7 on 2021-03-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210331_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publicationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
