# Generated by Django 3.1.7 on 2021-03-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210331_1447'),
    ]

    operations = [

        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
