# Generated by Django 3.1.7 on 2021-03-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210331_2031'),
    ]

    operations = [
    ]
